services:
  db:
    image: postgres:15-alpine
    container_name: meguru-postgres
    environment:
      POSTGRES_DB: meguru_db
      POSTGRES_USER: meguru_user
      POSTGRES_PASSWORD: meguru_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meguru-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meguru-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PORT: ${PORT}
    volumes:
      - .:/app
    networks:
      - meguru-network

volumes:
  postgres_data:

networks:
  meguru-network:
    driver: bridge 